baseURL = "https://metacrobe.github.io/"
publishDir = "public_build"
languageCode = "en-US"
title = "metacrobe"
theme = "bootstrap-bp-hugo-startpage"
# googleAnalytics = "UA-123-45"
copyright = "Sebastian Pech"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = false
paginate = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "public", "public_build"]

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[Author]
  name = "Jarrod J Scott"

[params]
  description = "metacrobe"
  #images = ["logo.jpg"]
  startPageColumns = false
  welcomeText = "Jarrod J Scott, PhD"

[[params.searchEngines]]
  name = "Google"
  activated = false
  url = "https://www.google.com/search"

[[params.searchEngines]]
  name = "DuckDuckGo"
  activated = false
  url = "https://duckduckgo.com/"

[[params.searchEngines]]
  name = "Bing"
  activated = false
  url = "https://www.bing.com/search"
